/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2020-03-09 04:55:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n");
      out.write("  Licensed to the Apache Software Foundation (ASF) under one or more\n");
      out.write("  contributor license agreements.  See the NOTICE file distributed with\n");
      out.write("  this work for additional information regarding copyright ownership.\n");
      out.write("  The ASF licenses this file to You under the Apache License, Version 2.0\n");
      out.write("  (the \"License\"); you may not use this file except in compliance with\n");
      out.write("  the License.  You may obtain a copy of the License at\n");
      out.write("\n");
      out.write("      http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write("\n");
      out.write("  Unless required by applicable law or agreed to in writing, software\n");
      out.write("  distributed under the License is distributed on an \"AS IS\" BASIS,\n");
      out.write("  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
      out.write("  See the License for the specific language governing permissions and\n");
      out.write("  limitations under the License.\n");
      out.write("-->\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!--[if lt IE 7]><html class=\"no-js lt-ie9 lt-ie8 lt-ie7\"><![endif]-->\n");
      out.write("<!--[if IE 7]><html class=\"no-js lt-ie9 lt-ie8\"><![endif]-->\n");
      out.write("<!--[if IE 8]><html class=\"no-js lt-ie9\"><![endif]-->\n");
      out.write("<!--[if gt IE 8]><!-->\n");
      out.write("<html class=\"no-js\">\n");
      out.write("\t<!--<![endif]-->\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"utf-8\">\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n");
      out.write("\t\t<title> Ranger - Sign In</title>\n");
      out.write("\t\t<meta name=\"description\" content=\"\">\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"images/favicon.ico\">\n");
      out.write("\t\t<link href=\"styles/bootstrap.min.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" id=\"bootstrap-css\">\n");
      out.write("\t\t<link href=\"styles/xa.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" >\n");
      out.write("                <script src=\"libs/bower/jquery/js/jquery-3.4.1.js\" ></script>\n");
      out.write("\t\t\n");
      out.write("\t\t<script src=\"scripts/prelogin/XAPrelogin.js\" ></script>\n");
      out.write("\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t$(document).ready(function() {\n");
      out.write("\t\t\t\tvar updateBoxPosition = function() {\n");
      out.write("\t\t\t\t\t$('#signin-container').css({\n");
      out.write("\t\t\t\t\t\t'margin-top' : ($(window).height() - $('#signin-container').height()) / 2\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t};\n");
      out.write("\t\t\t\t$(window).resize(updateBoxPosition);\n");
      out.write("\t\t\t\tvar queryParams = JSON.parse('{\"' + decodeURI((location.href.split('?')[1] || 'g=0').replace(/=/g, \"\\\":\\\"\")) + '\"}');\n");
      out.write("              \tif(queryParams.sessionTimeout){\n");
      out.write("                \twindow.alert('Session Timeout');\n");
      out.write("                \tlocation.replace(\"login.jsp\");\n");
      out.write("               \t}\n");
      out.write("\t\t\t\tsetTimeout(updateBoxPosition, 50);\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\n");
      out.write("\t</head>\n");
      out.write("\t<body class=\"login\" style=\"\">\n");
      out.write("\t\t");

			response.setHeader("X-Frame-Options", "DENY");
		
      out.write("\n");
      out.write("\t\t<!-- Page content\n");
      out.write("\t\t================================================== -->\n");
      out.write("\t\t<section id=\"signin-container\" style=\"margin-top: 4.5px;\">\n");
      out.write("\t\t\t<div class=\"l-logo\">\n");
      out.write("\t\t\t\t<img src=\"images/logo.png\" alt=\"Ranger logo\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<form action=\"\" method=\"post\" accept-charset=\"utf-8\">\n");
      out.write("\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t<div class=\"fields\">\n");
      out.write("\t\t\t\t\t\t<label><i class=\"icon-user\"></i> Username:</label>\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"username\" id=\"username\" tabindex=\"1\" autofocus>\n");
      out.write("\t\t\t\t\t\t<label><i class=\"icon-lock\"></i> Password:</label>\t\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"password\" tabindex=\"2\" autocomplete=\"off\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<span id=\"errorBox\" class=\"help-inline\" style=\"color:white;display:none;\"><span class=\"errorMsg\"></span>\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-warning-sign\" style=\"color:#ae2817;\"></i>\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t<span id=\"errorBoxUnsynced\" class=\"help-inline\" style=\"color:white;display:none;\">User is not available in HDP Admin Tool. Please contact your Administrator.\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-warning-sign\" style=\"color:#ae2817;\"></i>\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary btn-block\" id=\"signIn\" tabindex=\"4\" >\n");
      out.write("\t\t\t\t\t\tSign In\n");
      out.write("\t\t\t\t\t\t<i id=\"signInLoading\" class=\"icon-spinner icon-spin pull-right icon-sign-in\"></i>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</fieldset>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</section>\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
